version: "3"
services:
  web:
    image: nginx
    logging:
      driver: splunk
      options:
        splunk-url: http://<IP_Address>:8088
        splunk-token: <Splunk_Token>
        splunk-insecureskipverify: "true"
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
